services:
  fugo-v6:
    image: centrifugo/centrifugo:v6
    container_name: fugo-v6
    command: ["centrifugo", "-c", "/centrifugo/config.json"]
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/centrifugo/config.json:ro
    networks:
      - centrifugo_net

  centrifugo-proxy:
    image: nginx:1.25
    container_name: centrifugo-proxy
    depends_on:
      - fugo-v6
    ports:
      - "8080:8080"
      - "18080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # Dùng cùng network nội bộ
    networks:
      - centrifugo_net

networks:
  centrifugo_net:
    driver: bridge
